### ISSUE TITLE
CAMI support

### ISSUE THREAD

**Issue by ghost** [DaaOtt/maestro#67]
Hey,
There is a problem with your CAMI support.
I'm in the group root and CAMI.PlayerHasAccess with a 'superadmin' privilege returns nothing

**Comment by ottworks** [comment]
Oops, I wasn't using the callback.

**Comment by ghost** [comment]
Yes I saw that. It could be nice if you can fix it so my addon can support Maestro ;)

**Comment by ghost** [comment]
I found another problem :
When CAMI.PlayerHasAccess( ... ) is called, the third argument 'Target' is optional.
With Maestro, it returns a nil error if target isn't used.
