### ISSUE TITLE
Error at In-game Menu Target System

### ISSUE THREAD

**Issue by Dom-R** [DaaOtt/maestro#71]
When trying to target a player with the In-game Menu, the targeting system is using $1~X instead of the actual target name, resulting in 

> Query matched no players.

Example:
`[21:59] XXX(STEAM_0:1:XXXXXX): ms vac $1`

`[21:59] XXX(STEAM_0:1:XXXXXX): ms vac $1`

`[21:59] XXX(STEAM_0:1:XXXXXX): ms strip $1`

`[21:59] XXX(STEAM_0:1:XXXXXX): ms note $1`

`[21:59] XXX(STEAM_0:1:XXXXXX): ms note $1 test``

Tested without any other addon and with sandbox gamemode.

**Comment by ottworks** [comment]
$1 is a valid way to target players. You just don't  have permission to target them.

**Comment by ottworks** [comment]
I fixed this btw.

**Comment by Dom-R** [comment]
._.
