### ISSUE TITLE
All Settings Dumped on Server Restart

### ISSUE THREAD

**Issue by ReverendV92** [DaaOtt/maestro#73]
I'm having an issue where Maestro's setting don't persist across server restarts. All bans, ranks, etc get dumped when the server goes down. 

The server is a vanilla server running only Maestro so I don't understand what's causing it.

**Comment by ottworks** [comment]
Perhaps there's something wrong with database write privileges? What OS are you on?

**Comment by ReverendV92** [comment]
I'm in Windows 7 64-bit Ultimate. I'm having this issue with anything that requires access to SQL so it looks like it's not mutually exclusive.

**Comment by ReverendV92** [comment]
Regardless of relation to Maestro, do you have any idea what might be causing it? I'm unable to run a server effectively because this, PermaProps, and DarkRP all require SQL and none of them seem to be able to write or read from the .db files.

**Comment by ottworks** [comment]
It's unlikely, but maybe you're out of storage space? Things always act
unexpectedly when that happens.

**Comment by ReverendV92** [comment]
I'm not sure. I'm a novice programmer so I have no idea how to even view the *.db files effectively. I tried deleting them and they still refused to store the Maestro stuff. I got an error on server launch. I'll get it and reply with it.
