### ISSUE TITLE
maestro.ban doesn't call ply:Ban()

### ISSUE THREAD

**Issue by origintopleft** [DaaOtt/maestro#77]
This essentially makes !ban a glorified alias for !kick until someone with access to the server console runs `banid`.

Quick-n-dirty patch attached, just calls `ply:Ban(time, false)` before the existing maestro code.
[It's a zip file because GitHub for some bizarre reason doesn't accept .patch files](https://github.com/0tt/maestro/files/417140/maestro-ply-ban.zip)

**Comment by ottworks** [comment]
Database error. Will fix.
