### ISSUE TITLE
Temporary Ranking? BAddon Support

### ISSUE THREAD

**Issue by Septonix** [DaaOtt/maestro#83]
Is there any way so we can add a user to a group then it removes the group after the specific time is up?

E.g someone buys VIP 30Day, It will set them to VIP for 30d.

P.S Does Maestro support bWhitelist? Ive tried and it doesnt work?

**Comment by ottworks** [comment]
You can use the queue command to queue up commands to be run at a later date. Note that, for security reasons, commands sent from a player will only be ran when they're online. You'll have to run them from the server console if you want them to run no matter what.
